//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczelnia.h
//  @ Date : 24.05.2023
//  @ Author :
//
//


#if !defined(_UCZELNIA_H)
#define _UCZELNIA_H

#include <iostream>
#include <string>
#include <vector>

using namespace std;

#include "Uzytkownik.h"
#include "Student.h"
#include "Narzedzie.h"

class Uczelnia {
public:
	Uczelnia(string nazwa);
	void setNazwa(string nazwa);
	string getNazwa();
	void dodajUzytkownika(Uzytkownik* uzytkownik);
	void usunUzytkownika(string login);
	void dodajNarzedzie(Narzedzie* narzedzie);
	void usunNarzedzie(string nazwa);
	Uzytkownik* logowanie(string login, string haslo, bool czyStudent);
	Uzytkownik* rejestracja(string login, string haslo, bool czyStudent);
	void skorzystajZNarzedzia(string nazwa);
	Student* znajdzStudenta(string nrAlbumu);
private:
	string nazwa;
	vector <Uzytkownik*> uzytkownicy;
	vector <Narzedzie*> narzedzia;
};

#endif  //_UCZELNIA_H
