//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.h
//  @ Date : 24.05.2023
//  @ Author :
//
//


#if !defined(_UZYTKOWNIK_H)
#define _UZYTKOWNIK_H

#include <iostream>
#include <string>

using namespace std;

class Uzytkownik {
public:
	virtual void setLogin(string login);
	virtual string getLogin();
	virtual void setHaslo(string haslo);
	virtual string getHaslo();
	virtual void zalogujSie();
	virtual void wylogujSie();
	bool czyStudent;
protected:
	string login;
	string haslo;
	bool czyZalogowany;
};

#endif  //_UZYTKOWNIK_H
