//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.cpp
//  @ Date : 24.05.2023
//  @ Author :
//
//


#include "Uzytkownik.h"

void Uzytkownik::setLogin(string login) {
    this->login = login;
}

string Uzytkownik::getLogin() {
    return this->login;
}

void Uzytkownik::setHaslo(string haslo) {
    this->haslo = haslo;
}

string Uzytkownik::getHaslo() {
    return this->haslo;
}

void Uzytkownik::zalogujSie() {
    this->czyZalogowany = true;
    cout << "Zalogowano!\n";
}

void Uzytkownik::wylogujSie() {
    this->czyZalogowany = false;
    cout << "Wylogowano!\n";
}

