//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uzytkownik.h
//  @ Date : 24.05.2023
//  @ Author :
//
//


#if !defined(_UZYTKOWNIK_H)
#define _UZYTKOWNIK_H

#include <iostream>
#include <string>

using std::cout, std::cin;
using std::string;

class Uzytkownik {
public:
	void setLogin(string login);
	string getLogin();
	void setHaslo(string haslo);
	string getHaslo();
	void zalogujSie();
	void wylogujSie();
	bool czyStudent;
protected:
	string login;
	string haslo;
	bool czyZalogowany;
};

#endif  //_UZYTKOWNIK_H
